services:
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    container_name: django-react_server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
    depends_on:
      - db

  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    container_name: django-react_client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: