# Generated by Django 6.0.7 on 2026-08-05 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'UNASIGNED'), (2, 'ASSIGNED'), (3, 'WORKING'), (4, 'REVIEW'), (5, 'CLOSED')], default=1)),
                ('started_at', models.DateTimeField(null=True)),
                ('closed_at', models.DateTimeField(null=True)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'URGENT'), (2, 'CARRENT'), (3, 'CAN_WAIT'), (4, 'LATER')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
